/** Enum untuk Module 2 — Tracking & Assignment. */

export enum AssigneeType {
  USER = 'USER',
  DEPARTMENT = 'DEPARTMENT',
  LOCATION = 'LOCATION',
}

export enum TransferStatus {
  REQUESTED = 'REQUESTED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CONFIRMED = 'CONFIRMED',
}

export enum BorrowingStatus {
  REQUESTED = 'REQUESTED',
  BORROWED = 'BORROWED',
  RETURNED = 'RETURNED',
  REJECTED = 'REJECTED',
}

export enum HandoverRefType {
  ASSIGNMENT = 'ASSIGNMENT',
  TRANSFER = 'TRANSFER',
  BORROWING = 'BORROWING',
}

export enum AssetHistoryEvent {
  CREATED = 'CREATED',
  ASSIGNED = 'ASSIGNED',
  RELEASED = 'RELEASED',
  TRANSFER_REQUESTED = 'TRANSFER_REQUESTED',
  TRANSFER_APPROVED = 'TRANSFER_APPROVED',
  TRANSFER_REJECTED = 'TRANSFER_REJECTED',
  TRANSFERRED = 'TRANSFERRED',
  BORROW_REQUESTED = 'BORROW_REQUESTED',
  BORROWED = 'BORROWED',
  RETURNED = 'RETURNED',
  BORROW_REJECTED = 'BORROW_REJECTED',
  HANDOVER = 'HANDOVER',
}
