/** Jenis laporan (FR-M7). */
export enum ReportType {
  INVENTORY = 'INVENTORY',
  LOCATION = 'LOCATION',
  ASSIGNMENT = 'ASSIGNMENT',
  MAINTENANCE = 'MAINTENANCE',
  DEPRECIATION = 'DEPRECIATION',
  DISPOSAL = 'DISPOSAL',
}
